spring:
  application:
    name: banking-app
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

#    datasource:
#      url: ${DB_URL:jdbc:postgresql://localhost:5432/bankdb}
#      username: ${DB_USER:sa}
#      password: ${DB_PASSWORD:secret}
#      driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
#
#      jpa:
#        hibernate:
#          ddl-auto: update
#        database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
#        show-sql: false

  h2:
    console:
      enabled: true  # Access at /h2-console
  security:
    user:
      name: admin
      password: adminpass  # Basic auth for testing
#jwt:
#  secret: "WnJ4TnF1eUo0b1NMeUZKb1R3eE5Yd2YyYjV4bXNhbnB1d3JxM2xHMQ=="
#  expiration-ms: 86400000
jwt:
  secret: ${JWT_SECRET:WnJ4TnF1eUo0b1NMeUZKb1R3eE5Yd2YjV4bXNhbnB1d3JxM2xHMQ==}
  expiration-ms: 86400000  # 1 day in milliseconds

logging:
  level:
    com.example.bankingapp: INFO
