# .github/workflows/ci.yml
name: CI/CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: bankdb
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: secret
        ports: [5432:5432]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with: { java-version: '17', distribution: 'temurin' }
      - name: Build & Test
        run: ./mvnw -B verify
      - name: Docker build
        run: |
          docker build -t banking-app .
      - name: Push to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag banking-app ghcr.io/${{ github.repository }}:latest
      - run: docker push ghcr.io/${{ github.repository }}:latest